// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: proto/metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricServiceClient is the client API for MetricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricServiceClient interface {
	SetMultiParam(ctx context.Context, in *SetMultiParamRequest, opts ...grpc.CallOption) (*SetMultiParamResponse, error)
	GetParam(ctx context.Context, in *GetParamRequest, opts ...grpc.CallOption) (*GetParamResponse, error)
	GetAllParams(ctx context.Context, in *GetAllParamsRequest, opts ...grpc.CallOption) (*GetAllParamsResponse, error)
}

type metricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricServiceClient(cc grpc.ClientConnInterface) MetricServiceClient {
	return &metricServiceClient{cc}
}

func (c *metricServiceClient) SetMultiParam(ctx context.Context, in *SetMultiParamRequest, opts ...grpc.CallOption) (*SetMultiParamResponse, error) {
	out := new(SetMultiParamResponse)
	err := c.cc.Invoke(ctx, "/internal.MetricService/SetMultiParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceClient) GetParam(ctx context.Context, in *GetParamRequest, opts ...grpc.CallOption) (*GetParamResponse, error) {
	out := new(GetParamResponse)
	err := c.cc.Invoke(ctx, "/internal.MetricService/GetParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceClient) GetAllParams(ctx context.Context, in *GetAllParamsRequest, opts ...grpc.CallOption) (*GetAllParamsResponse, error) {
	out := new(GetAllParamsResponse)
	err := c.cc.Invoke(ctx, "/internal.MetricService/GetAllParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricServiceServer is the server API for MetricService service.
// All implementations must embed UnimplementedMetricServiceServer
// for forward compatibility
type MetricServiceServer interface {
	SetMultiParam(context.Context, *SetMultiParamRequest) (*SetMultiParamResponse, error)
	GetParam(context.Context, *GetParamRequest) (*GetParamResponse, error)
	GetAllParams(context.Context, *GetAllParamsRequest) (*GetAllParamsResponse, error)
	mustEmbedUnimplementedMetricServiceServer()
}

// UnimplementedMetricServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetricServiceServer struct {
}

func (UnimplementedMetricServiceServer) SetMultiParam(context.Context, *SetMultiParamRequest) (*SetMultiParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMultiParam not implemented")
}
func (UnimplementedMetricServiceServer) GetParam(context.Context, *GetParamRequest) (*GetParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParam not implemented")
}
func (UnimplementedMetricServiceServer) GetAllParams(context.Context, *GetAllParamsRequest) (*GetAllParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllParams not implemented")
}
func (UnimplementedMetricServiceServer) mustEmbedUnimplementedMetricServiceServer() {}

// UnsafeMetricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricServiceServer will
// result in compilation errors.
type UnsafeMetricServiceServer interface {
	mustEmbedUnimplementedMetricServiceServer()
}

func RegisterMetricServiceServer(s grpc.ServiceRegistrar, srv MetricServiceServer) {
	s.RegisterService(&MetricService_ServiceDesc, srv)
}

func _MetricService_SetMultiParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMultiParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).SetMultiParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.MetricService/SetMultiParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).SetMultiParam(ctx, req.(*SetMultiParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricService_GetParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).GetParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.MetricService/GetParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).GetParam(ctx, req.(*GetParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricService_GetAllParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).GetAllParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.MetricService/GetAllParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).GetAllParams(ctx, req.(*GetAllParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricService_ServiceDesc is the grpc.ServiceDesc for MetricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.MetricService",
	HandlerType: (*MetricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMultiParam",
			Handler:    _MetricService_SetMultiParam_Handler,
		},
		{
			MethodName: "GetParam",
			Handler:    _MetricService_GetParam_Handler,
		},
		{
			MethodName: "GetAllParams",
			Handler:    _MetricService_GetAllParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metrics.proto",
}
